import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import connectDB from "./config/db.js";
import User from "./models/User.js";
import Product from "./models/Product.js";
import { PRODUCT_IMAGES } from "./data/productImages.js";

dotenv.config();

const img = (name) => [PRODUCT_IMAGES[name]];

const seedData = async () => {
  try {
    await connectDB();

    await User.deleteMany();
    await Product.deleteMany();

    const salt = await bcrypt.genSalt(10);
    const adminPassword = await bcrypt.hash("admin123", salt);
    const userPassword = await bcrypt.hash("user123", salt);

    await User.create([
      { name: "Admin", email: "admin@shopez.com", password: adminPassword, role: "admin" },
      { name: "John Doe", email: "user@shopez.com", password: userPassword, role: "user" },
    ]);

    const products = [
      {
        name: "Samsung Galaxy S24 Ultra",
        description: "Latest flagship smartphone with AI features, 200MP camera, and S Pen support.",
        category: "Electronics",
        brand: "Samsung",
        price: 129999,
        originalPrice: 149999,
        stock: 50,
        images: img("Samsung Galaxy S24 Ultra"),
        rating: 4.8,
        numReviews: 234,
        isFeatured: true,
        isTrending: true,
        discount: 13,
      },
      {
        name: "Apple iPhone 15 Pro",
        description: "Titanium design with A17 Pro chip, Action button, and USB-C.",
        category: "Electronics",
        brand: "Apple",
        price: 134900,
        originalPrice: 144900,
        stock: 30,
        images: img("Apple iPhone 15 Pro"),
        rating: 4.9,
        numReviews: 567,
        isFeatured: true,
        isTrending: true,
        discount: 7,
      },
      {
        name: "Sony WH-1000XM5 Headphones",
        description: "Industry-leading noise cancellation with 30-hour battery life.",
        category: "Electronics",
        brand: "Sony",
        price: 29990,
        originalPrice: 34990,
        stock: 100,
        images: img("Sony WH-1000XM5 Headphones"),
        rating: 4.7,
        numReviews: 189,
        isFeatured: true,
        discount: 14,
      },
      {
        name: "Nike Air Max 270",
        description: "Iconic Air Max cushioning with breathable mesh upper.",
        category: "Fashion",
        brand: "Nike",
        price: 12995,
        originalPrice: 15995,
        stock: 75,
        images: img("Nike Air Max 270"),
        rating: 4.5,
        numReviews: 312,
        isTrending: true,
        discount: 19,
      },
      {
        name: "Levi's 501 Original Jeans",
        description: "Classic straight fit jeans with button fly and authentic vintage look.",
        category: "Fashion",
        brand: "Levi's",
        price: 3999,
        originalPrice: 4999,
        stock: 120,
        images: img("Levi's 501 Original Jeans"),
        rating: 4.4,
        numReviews: 156,
        isNewArrival: true,
        discount: 20,
      },
      {
        name: "Organic Basmati Rice 5kg",
        description: "Premium aged basmati rice, perfect for biryanis and pulao.",
        category: "Groceries",
        brand: "India Gate",
        price: 599,
        originalPrice: 699,
        stock: 200,
        images: img("Organic Basmati Rice 5kg"),
        rating: 4.6,
        numReviews: 89,
        isFeatured: true,
        discount: 14,
      },
      {
        name: "Fortune Sunflower Oil 5L",
        description: "Refined sunflower oil, light and healthy for everyday cooking.",
        category: "Groceries",
        brand: "Fortune",
        price: 749,
        originalPrice: 849,
        stock: 150,
        images: img("Fortune Sunflower Oil 5L"),
        rating: 4.3,
        numReviews: 67,
        isFeatured: true,
        discount: 12,
      },
      {
        name: "Tata Tea Gold 1kg",
        description: "Premium blend tea with rich aroma and refreshing taste.",
        category: "Groceries",
        brand: "Tata",
        price: 520,
        originalPrice: 580,
        stock: 180,
        images: img("Tata Tea Gold 1kg"),
        rating: 4.5,
        numReviews: 210,
        isFeatured: true,
        isTrending: true,
        discount: 10,
      },
      {
        name: "Aashirvaad Wheat Flour 5kg",
        description: "100% whole wheat atta for soft rotis and parathas.",
        category: "Groceries",
        brand: "Aashirvaad",
        price: 280,
        originalPrice: 320,
        stock: 300,
        images: img("Aashirvaad Wheat Flour 5kg"),
        rating: 4.7,
        numReviews: 445,
        isNewArrival: true,
        discount: 13,
      },
      {
        name: "Dabur Honey 500g",
        description: "Pure, natural honey sourced from the finest beekeepers.",
        category: "Groceries",
        brand: "Dabur",
        price: 199,
        originalPrice: 249,
        stock: 250,
        images: img("Dabur Honey 500g"),
        rating: 4.4,
        numReviews: 178,
        isNewArrival: true,
        discount: 20,
      },
      {
        name: "Lakme Absolute Matte Lipstick",
        description: "Long-lasting matte finish lipstick in 20 stunning shades.",
        category: "Beauty",
        brand: "Lakme",
        price: 695,
        originalPrice: 895,
        stock: 300,
        images: img("Lakme Absolute Matte Lipstick"),
        rating: 4.5,
        numReviews: 423,
        isTrending: true,
        isNewArrival: true,
        discount: 22,
      },
      {
        name: "Maybelline Fit Me Foundation",
        description: "Natural matte foundation for all skin types, SPF 18.",
        category: "Beauty",
        brand: "Maybelline",
        price: 549,
        originalPrice: 649,
        stock: 250,
        images: img("Maybelline Fit Me Foundation"),
        rating: 4.4,
        numReviews: 278,
        isNewArrival: true,
        discount: 15,
      },
      {
        name: "Himalaya Face Wash 150ml",
        description: "Gentle purifying face wash for clear, refreshed skin.",
        category: "Beauty",
        brand: "Himalaya",
        price: 175,
        originalPrice: 225,
        stock: 400,
        images: img("Himalaya Face Wash 150ml"),
        rating: 4.3,
        numReviews: 567,
        isTrending: true,
        discount: 22,
      },
      {
        name: "Fogg Perfume Body Spray",
        description: "Long-lasting fragrance for all-day freshness.",
        category: "Beauty",
        brand: "Fogg",
        price: 249,
        originalPrice: 349,
        stock: 350,
        images: img("Fogg Perfume Body Spray"),
        rating: 4.2,
        numReviews: 890,
        isNewArrival: true,
        isFeatured: true,
        discount: 29,
      },
      {
        name: "Nivea Soft Moisturizing Cream",
        description: "Light, non-greasy moisturizer for face and body.",
        category: "Beauty",
        brand: "Nivea",
        price: 299,
        originalPrice: 399,
        stock: 280,
        images: img("Nivea Soft Moisturizing Cream"),
        rating: 4.6,
        numReviews: 345,
        isFeatured: true,
        discount: 25,
      },
      {
        name: "IKEA MALM Bed Frame",
        description: "Modern bed frame with storage drawers, queen size.",
        category: "Home",
        brand: "IKEA",
        price: 24999,
        originalPrice: 29999,
        stock: 20,
        images: img("IKEA MALM Bed Frame"),
        rating: 4.6,
        numReviews: 45,
        isFeatured: true,
        discount: 17,
      },
      {
        name: "Philips Air Fryer HD9200",
        description: "Rapid Air technology for healthy frying with 90% less fat.",
        category: "Home",
        brand: "Philips",
        price: 8999,
        originalPrice: 10999,
        stock: 40,
        images: img("Philips Air Fryer HD9200"),
        rating: 4.7,
        numReviews: 134,
        isFeatured: true,
        isTrending: true,
        discount: 18,
      },
      {
        name: "Wakefit Memory Foam Cushion",
        description: "Ergonomic cushion for superior sitting comfort.",
        category: "Home",
        brand: "Wakefit",
        price: 899,
        originalPrice: 1299,
        stock: 150,
        images: img("Wakefit Memory Foam Cushion"),
        rating: 4.4,
        numReviews: 267,
        isTrending: true,
        discount: 31,
      },
      {
        name: "Milton Dining Set 6 Pieces",
        description: "Elegant stainless steel dining set for family meals.",
        category: "Home",
        brand: "Milton",
        price: 1499,
        originalPrice: 1999,
        stock: 80,
        images: img("Milton Dining Set 6 Pieces"),
        rating: 4.5,
        numReviews: 123,
        isNewArrival: true,
        discount: 25,
      },
      {
        name: "Eureka Forbes Vacuum Cleaner",
        description: "Powerful suction vacuum for deep home cleaning.",
        category: "Home",
        brand: "Eureka Forbes",
        price: 6999,
        originalPrice: 8999,
        stock: 35,
        images: img("Eureka Forbes Vacuum Cleaner"),
        rating: 4.3,
        numReviews: 89,
        isFeatured: true,
        discount: 22,
      },
      {
        name: "Yonex Badminton Racket",
        description: "Professional grade carbon fiber racket with isometric head shape.",
        category: "Sports",
        brand: "Yonex",
        price: 4999,
        originalPrice: 5999,
        stock: 60,
        images: img("Yonex Badminton Racket"),
        rating: 4.8,
        numReviews: 98,
        isNewArrival: true,
        discount: 17,
      },
      {
        name: "Adidas Ultraboost 22",
        description: "Responsive Boost midsole with Primeknit upper for ultimate comfort.",
        category: "Sports",
        brand: "Adidas",
        price: 15999,
        originalPrice: 18999,
        stock: 45,
        images: img("Adidas Ultraboost 22"),
        rating: 4.6,
        numReviews: 201,
        isFeatured: true,
        isTrending: true,
        discount: 16,
      },
      {
        name: "SG Cricket Bat English Willow",
        description: "Professional grade cricket bat for power hitting.",
        category: "Sports",
        brand: "SG",
        price: 3499,
        originalPrice: 4499,
        stock: 40,
        images: img("SG Cricket Bat English Willow"),
        rating: 4.5,
        numReviews: 156,
        isTrending: true,
        discount: 22,
      },
      {
        name: "Strauss Yoga Mat 6mm",
        description: "Anti-slip yoga mat with carrying strap included.",
        category: "Sports",
        brand: "Strauss",
        price: 799,
        originalPrice: 1299,
        stock: 120,
        images: img("Strauss Yoga Mat 6mm"),
        rating: 4.4,
        numReviews: 234,
        isNewArrival: true,
        discount: 38,
      },
      {
        name: "Nivia Football Size 5",
        description: "FIFA approved football for turf and grass play.",
        category: "Sports",
        brand: "Nivia",
        price: 599,
        originalPrice: 899,
        stock: 100,
        images: img("Nivia Football Size 5"),
        rating: 4.3,
        numReviews: 178,
        isFeatured: true,
        discount: 33,
      },
      {
        name: "MacBook Air M3",
        description: "13.6-inch Liquid Retina display, M3 chip, 18-hour battery life.",
        category: "Electronics",
        brand: "Apple",
        price: 114900,
        originalPrice: 124900,
        stock: 25,
        images: img("MacBook Air M3"),
        rating: 4.9,
        numReviews: 345,
        isFeatured: true,
        isNewArrival: true,
        discount: 8,
      },
      {
        name: "Boat Airdopes 131",
        description: "True wireless earbuds with 60-hour playback and ENx technology.",
        category: "Electronics",
        brand: "Boat",
        price: 999,
        originalPrice: 2990,
        stock: 500,
        images: img("Boat Airdopes 131"),
        rating: 4.2,
        numReviews: 1200,
        isTrending: true,
        discount: 67,
      },
      {
        name: "Puma Essentials Hoodie",
        description: "Comfortable cotton blend hoodie with kangaroo pocket.",
        category: "Fashion",
        brand: "Puma",
        price: 2499,
        originalPrice: 3499,
        stock: 80,
        images: img("Puma Essentials Hoodie"),
        rating: 4.3,
        numReviews: 87,
        isNewArrival: true,
        discount: 29,
      },
      {
        name: "Zara Cotton Formal Shirt",
        description: "Slim fit cotton shirt perfect for office and casual wear.",
        category: "Fashion",
        brand: "Zara",
        price: 2990,
        originalPrice: 3990,
        stock: 90,
        images: img("Zara Cotton Formal Shirt"),
        rating: 4.5,
        numReviews: 134,
        isFeatured: true,
        isTrending: true,
        discount: 25,
      },
      {
        name: "H&M Floral Summer Dress",
        description: "Lightweight floral print dress for everyday elegance.",
        category: "Fashion",
        brand: "H&M",
        price: 1999,
        originalPrice: 2799,
        stock: 65,
        images: img("H&M Floral Summer Dress"),
        rating: 4.6,
        numReviews: 92,
        isNewArrival: true,
        discount: 29,
      },
      {
        name: "Ratnagiri Mango",
        description: "Premium Alphonso mangoes from Ratnagiri — sweet, juicy and naturally ripened.",
        category: "Groceries",
        brand: "Farm Fresh",
        price: 800,
        originalPrice: 999,
        stock: 100,
        images: img("Ratnagiri Mango"),
        rating: 4.7,
        numReviews: 267,
        isFeatured: true,
        isTrending: true,
        isNewArrival: true,
        discount: 20,
      },
    ];

    await Product.insertMany(products);

    console.log("Database seeded successfully!");
    console.log("Admin: admin@shopez.com / admin123");
    console.log("User: user@shopez.com / user123");
    process.exit(0);
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }
};

seedData();
